### ISSUE TITLE
Assembly already exists error

### ISSUE THREAD

**Issue by linojon** [coder89/arfoundation-mock#1]
hi, i tried importing the unitypackage and get the following errors in the attached console log

Unity 2018.4.1f1
AR Foundation 1.5.0-preview.3
ARCore XR Plugin 2.1.0-preview.5
ARKit XR Plugin 2.1.0-preivew.5
XR Remoting 0.0.1-preview.10

[Editor.log](https://github.com/coder89/arfoundation-mock/files/3241902/Editor.log)

**Comment by linojon** [comment]
i also tried removing the XR Remoting 0.0.1 package with similar errors (not sure if your package replaces it or adds onto)

**Comment by coder89** [comment]
Hi,

You should probably remove both xr.remoting and xr.mock packages from Unity project first (you can edit the package manifest in notepad to make sure it's not there). Also I have not tested with Unity 2018 so not sure if this could also be another reason for this error. I use 2019.1.

**Comment by coder89** [comment]
Try cloning the repo and opening the sample scene. If that works then you need to make some chnages to your project to mimic the SampleScene.

I can only say the famous words: "it works on my machine" :)

**Comment by coder89** [comment]
I created a new release in case you got type error related to "ARPlaneVisualizer".
